version: '3'
networks:
  sextant:
services:
  router:
    image: binocarlos/noxy
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
    environment:
      - NOXY_DEFAULT_HOST=frontend
      - NOXY_DEFAULT_PORT=80
      - NOXY_API_FRONT=/api/v1
      - NOXY_API_HOST=api
      - NOXY_PROXY_FRONT=/proxy
      - NOXY_PROXY_HOST=api
    networks:
     - sextant
  frontend:
    image: blockchaintp/sextant:master
    environment:
      - NODE_ENV=production
    networks:
     - sextant
  api:
    image: blockchaintp/sextant-api:master
    environment:
      - NODE_ENV=production
      - SEXTANT_FILE_STORE_FOLDER=/filestore-data
    volumes:
      - ./.data/filestore-data:/filestore-data
    networks:
     - sextant