# the following variables MUST be present in the environment
#
#  * POSTGRES_USER
#  * POSTGRES_DB
#  * POSTGRES_PASSWORD
#  * SESSION_SECRET
#  * TOKEN_SECRET
#
version: '3'
volumes:
  postgres-data:
networks:
  sextant:
services:
  router:
    image: binocarlos/noxy
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
    environment:
      - NOXY_DEFAULT_HOST=frontend
      - NOXY_DEFAULT_PORT=80
      - NOXY_API_FRONT=/api/v1
      - NOXY_API_HOST=api
    networks:
     - sextant
  postgres:
    image: postgres:9.6.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
     - sextant
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
  frontend:
    image: blockchaintp/sextant:master
    networks:
     - sextant
    environment:
      - NODE_ENV=production
  api:
    image: blockchaintp/sextant-api:master
    networks:
     - sextant
    environment:
      - NODE_ENV=production
      - LOGGING=1
      - POSTGRES_SERVICE_HOST=postgres
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - SESSION_SECRET
      - TOKEN_SECRET