version: '3'
volumes:
  postgres-data:
services:
  router:
    image: binocarlos/noxy
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
    environment:
      - NOXY_DEFAULT_HOST=frontend
      - NOXY_DEFAULT_PORT=8080
      - NOXY_DEFAULT_WS=1
      - NOXY_API_FRONT=/api/v1
      - NOXY_API_HOST=api
      - NOXY_PROXY_FRONT=/proxy
      - NOXY_PROXY_HOST=api
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  frontend:
    build:
      context: ../sextant
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    entrypoint: bash -c 'if [ -n "$MANUALRUN" ]; then tail -f /dev/null; else npm run develop; fi'
    environment:
      - NODE_ENV=development
      - MANUALRUN
    volumes:
      - ../sextant/src:/app/frontend/src
      - ../sextant/config:/app/frontend/config
      - ../sextant/dist:/app/frontend/dist
      - ../sextant/editions/dev.js:/app/frontend/src/edition.js
  api:
    build:
      context: ../sextant-api
      dockerfile: Dockerfile
      args:
        METERING_MODULE: aws_sfs.js
    entrypoint: bash -c 'if [ -n "$MANUALRUN" ]; then tail -f /dev/null; else npm run serve; fi'
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - MANUALRUN
      - POSTGRES_SERVICE_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - SESSION_SECRET=sextant
      - TOKEN_SECRET=sextant
      - LOGGING=1
