version: '3.2'
networks:
  default:
    external: true
    name: sextant-dev_default
services:
  taekion:
    build: 
      context: .
    privileged: true
    init: true
    entrypoint: bash -c 'mkdir -p /home/user/tfs_mount/data && tfs-fuse --allow-other -v $VOLUME_NAME -m /home/user/tfs_mount/data && tail -f /dev/null'
    devices:
      - "/dev/fuse"
    cap_add:
      - SYS_ADMIN
    environment:
      - TFS_URL
      - VOLUME_NAME
    volumes:
      - type: bind
        source: /tmp/tfs_mount
        target: /home/user/tfs_mount
        bind:
          propagation: rshared
  app:
    image: ubuntu
    entrypoint: bash -c 'tail -f /dev/null'
    depends_on: 
      - taekion
    volumes:
      - type: bind
        source: /tmp/tfs_mount
        target: /var/lib/tfs
        bind:
          propagation: rshared