apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sextant
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: sextant-api:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
        - name: POSTGRES_SERVICE_HOST
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: SESSION_SECRET
          value: sextant
        - name: TOKEN_SECRET
          value: sextant